#!/usr/bin/env python
# Each new term in the Fibonacci sequence is generated by adding the previous
# two terms. By starting with 1 and 2, the first 10 terms will be:
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# By considering the terms in the Fibonacci sequence whose values do not exceed
# four million, find the sum of the even-valued terms.

from itertools import takewhile

def main():
    print(sum(takewhile(lambda x: x < 4000000, evenFibonacci())));

def evenFibonacci():
    fibonacciGenerator = fibonacci()
    while True:
        n = fibonacciGenerator.next()
        if (n % 2 == 0):
            yield n

def fibonacci():
    last = 1
    current = 1
    while True:
        temp = current
        current += last
        last = temp
        yield last

if __name__ == "__main__":
    main()
